#ifndef __MAC_CONFIG_H__
#define __MAC_CONFIG_H__

#include <inttypes.h>

#define MAC_CONFIG_MAX_PAYLOAD_LENGTH 16
#define MAC_CONFIG_MAX_FRAME_POOL 32
#define MAC_CONFIG_MAX_ADDRESS_LIST 20
#define MAC_CONFIG_MAX_QUEUE_TX 10
#define MAC_CONFIG_MAX_QUEUE_STORE 10
#define MAC_CONFIG_MAX_QUEUE_ADDRESS 10
#define MAC_CONFIG_MAX_FRAME_BUFFER (12 + MAC_CONFIG_MAX_PAYLOAD_LENGTH)
#define MAC_CONFIG_MAX_RETRIES 3
#define MAC_CONFIG_MAX_ACK_ERROR 3

#define MAC_CONST_USE_EXTENDED_ADDRESS 0xfffe
#define MAC_CONST_BROADCAST_ADDRESS 0xffff

typedef struct {
  uint32_t ExtendedAddress;
} MAC_Config;

#endif // __MAC_CONFIG_H__
