#ifndef __MAC_CONFIG_H__
#define __MAC_CONFIG_H__

#define MAC_CONFIG_MAX_PAYLOAD_LENGTH 16
#define MAC_CONFIG_MAX_FRAME_POOL 32
#define MAC_CONFIG_MAX_ADDRESS_LIST 20
#define MAC_CONFIG_MAX_QUEUE_TX 10
#define MAC_CONFIG_MAX_QUEUE_STORE 10
#define MAC_CONFIG_MAX_QUEUE_ADDRESS 10
#define MAC_CONFIG_MAX_FRAME_BUFFER (4 + MAC_CONFIG_MAX_PAYLOAD_LENGTH)

#define MAC_CONFIG_EXTENDED_ADDRESS 0x12345678

#endif // __MAC_CONFIG_H__