#ifndef __MAC_COMMON_H__
#define __MAC_COMMON_H__

/* Enumeration types */
typedef enum {
  MAC_STATUS_OK,
  MAC_STATUS_INVALID_PARAM,
  MAC_STATUS_INVALID_CHECKSUM,
  MAC_STATUS_INVALID_LENGTH,
  MAC_STATUS_INVALID_DESTINATION,
  MAC_STATUS_INVALID_SOURCE,
  MAC_STATUS_INVALID_COMMAND,
  MAC_STATUS_MEMORY_ERROR,
  MAC_STATUS_NO_DELAY,
  MAC_STATUS_NO_DATA,
  MAC_STATUS_NO_ACK
} MAC_Status;

#endif // __MAC_COMMON_H__
